VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IVersion"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Sub Add()

End Sub
Public Sub Commit()

End Sub

Public Sub Revert()

End Sub
Public Sub Log()

End Sub

Public Sub Locked()

End Sub

Public Sub Unlocked()

End Sub

Public Sub Update()

End Sub

Public Sub Diff()

End Sub
Public Sub Brouser()

End Sub
Public Sub Ver()

End Sub
Public Sub Cleanup()

End Sub
Public Sub Help()

End Sub
